name: smart_alert_app
description: Smart Alert System - hospital roster & emergency dispatch with AI assistant
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  intl: ^0.18.1
  url_launcher: ^6.1.10
  share_plus: ^7.2.0
  path_provider: ^2.1.1
  http: ^0.13.6
  flutter_dotenv: ^5.1.0  
  file_picker: ^6.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env